# Generated by Django 5.2.7 on 2025-11-09 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('rojo', 'Rojo'), ('rosa', 'Rosa'), ('blanco', 'Blanco'), ('amarillo', 'Amarillo'), ('naranja', 'Naranja'), ('morado', 'Morado'), ('azul', 'Azul'), ('multicolor', 'Multicolor')], default='rojo', max_length=20)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, default='🌹', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('bodas', 'Bodas'), ('cumpleanos', 'Cumpleaños'), ('aniversario', 'Aniversario'), ('funeral', 'Funeral'), ('corporativo', 'Evento Corporativo'), ('san_valentin', 'San Valentín'), ('dia_madre', 'Día de la Madre')], default='bodas', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion_entrega',
            field=models.TextField(default='Misma dirección del cliente'),
        ),
        migrations.CreateModel(
            name='DiseñoRamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estilo', models.CharField(choices=[('clasico', 'Clásico'), ('moderno', 'Moderno'), ('rustico', 'Rústico'), ('romantico', 'Romántico'), ('minimalista', 'Minimalista')], default='clasico', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('diseño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.diseñoramo')),
                ('flor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.flor')),
            ],
        ),
    ]
