# Generated by Django 5.2.7 on 2025-12-15 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_flor_alter_categoria_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleramo',
            name='flor',
        ),
        migrations.AddField(
            model_name='detalleramo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
    ]
